// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiTPI_7K2wNYa1BfmMnpuV0cMnYJIdOls',
    appId: '1:970562413262:web:c82b51a4b3f0825e20669f',
    messagingSenderId: '970562413262',
    projectId: 'movieandtv-flutter',
    authDomain: 'movieandtv-flutter.firebaseapp.com',
    storageBucket: 'movieandtv-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAscLQvYS3mCsgvKkf1-KTGGIQdnHnuLyI',
    appId: '1:970562413262:android:9b036a1c2bde38b320669f',
    messagingSenderId: '970562413262',
    projectId: 'movieandtv-flutter',
    storageBucket: 'movieandtv-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_QvI0_YuiJABYHqv1VOjlYLxqNSgflmk',
    appId: '1:970562413262:ios:7c5365b7b0e54f2320669f',
    messagingSenderId: '970562413262',
    projectId: 'movieandtv-flutter',
    storageBucket: 'movieandtv-flutter.appspot.com',
    androidClientId: '970562413262-2pkrjg600902ed9taodqbaet48uqmbmv.apps.googleusercontent.com',
    iosClientId: '970562413262-7qgh7ehsqlislem92qg4ibge2v6fk7lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesandtvFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_QvI0_YuiJABYHqv1VOjlYLxqNSgflmk',
    appId: '1:970562413262:ios:d3d5fbd23578663620669f',
    messagingSenderId: '970562413262',
    projectId: 'movieandtv-flutter',
    storageBucket: 'movieandtv-flutter.appspot.com',
    androidClientId: '970562413262-2pkrjg600902ed9taodqbaet48uqmbmv.apps.googleusercontent.com',
    iosClientId: '970562413262-vsj0k53jbgu3uq8g3v3li84iae1sechp.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesandtvFlutter.RunnerTests',
  );
}
